server:
  port: 8083
  error:
    path: "/error"
    whitelabel:
      enabled: false
spring:
  datasource:
    url: "jdbc:mysql://192.168.0.106:3306/spring_social?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false"
    username: "dung"
    password: "!@B17dccn160"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 731079018552-0qjvepqgu19nvanqhud535ns251d1duh.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 681041120123721
            clientSecret: 3fd1d4c8f1589ab2548b705ed0b426d3
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: 42af461cac244812c5a5
            clientSecret: 7809c1bbc8c095933155a41ea160351240eff9d0
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
    # Bỏ tính năng cache của thymeleaf để lập trình cho nhanh
  thymeleaf:
    cache: false
    # Các message tĩnh sẽ được lưu tại thư mục i18n
  messages:
    basename: i18n/messages
    # Bỏ properties này đi khi deploy
    # Nó có tác dụng cố định ngôn ngữ hiện tại chỉ là Tiếng Việt
#  mvc:
    # Mặc định ngôn ngữ là tiếng việt
#    locale-resolver: fixed
#    locale: vi_VN
  # Đổi thành tiếng anh bằng cách bỏ comment ở dứoi
  # spring.mvc.locale=en_US
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8083
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
          # Để cái này cho angular
#      - http://localhost:4200/oauth2
#      - http://localhost:4200/mvc/login
      - http://localhost:8083/mvc/shop
      - http://localhost:8083/mvc/login
  secret:
    user: "dungntptit150699"
